// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Data.Context;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(RiskControlDbContext))]
    [Migration("20230417081402_userRoles")]
    partial class userRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("app.Data.Entity.CaseStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CaseStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 849, DateTimeKind.Local).AddTicks(2952),
                            Status = "CREATED"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 849, DateTimeKind.Local).AddTicks(2981),
                            Status = "REJECTED"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 849, DateTimeKind.Local).AddTicks(2984),
                            Status = "CLOSED"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 849, DateTimeKind.Local).AddTicks(2987),
                            Status = "ASSIGNED"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 849, DateTimeKind.Local).AddTicks(2991),
                            Status = "INVESTIGATING"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 849, DateTimeKind.Local).AddTicks(2993),
                            Status = "PENDING"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 849, DateTimeKind.Local).AddTicks(2997),
                            Status = "APPROVED"
                        });
                });

            modelBuilder.Entity("app.Data.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Example Agency",
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5745)
                        });
                });

            modelBuilder.Entity("app.Data.Entity.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmployeeType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 849, DateTimeKind.Local).AddTicks(3339),
                            Name = "Permanent"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 849, DateTimeKind.Local).AddTicks(3344),
                            Name = "Contract"
                        });
                });

            modelBuilder.Entity("app.Data.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "EX01",
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5837),
                            Price = 1m,
                            ProductName = "Example Claim case",
                            Status = "CREATED",
                            StatusId = 1,
                            UnitOfMeasureId = 1
                        });
                });

            modelBuilder.Entity("app.Data.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "POA",
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4646),
                            Name = "portal-admin"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CAM",
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4650),
                            Name = "client-admin"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CCR",
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4653),
                            Name = "client-creator"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CAS",
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4655),
                            Name = "client-assigner"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CSS",
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4659),
                            Name = "client-assessor"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AAM",
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4661),
                            Name = "agency-admin"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AAS",
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4664),
                            Name = "agency-supervisor"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AAA",
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4666),
                            Name = "agency-agent"
                        });
                });

            modelBuilder.Entity("app.Data.Entity.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Store", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5646),
                            StoreCode = "EX01",
                            StoreName = "Example Client Company"
                        });
                });

            modelBuilder.Entity("app.Data.Entity.StoreStock", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StoreId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("StoreStock", (string)null);
                });

            modelBuilder.Entity("app.Data.Entity.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToStoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("ToStoreId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("app.Data.Entity.TransactionDetail", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransactionId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("TransactionDetail", (string)null);
                });

            modelBuilder.Entity("app.Data.Entity.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TransactionType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(3947),
                            TransactionTypeName = "Stock Receipt"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4011),
                            TransactionTypeName = "Stock Out"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4014),
                            TransactionTypeName = "Transfer"
                        });
                });

            modelBuilder.Entity("app.Data.Entity.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isocode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasureName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasure");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4529),
                            Isocode = "CC",
                            UnitOfMeasureName = "Comprehensive"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4538),
                            Isocode = "NC",
                            UnitOfMeasureName = "Non-Comprehensive"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(4543),
                            Isocode = "OC",
                            UnitOfMeasureName = "Other"
                        });
                });

            modelBuilder.Entity("app.Data.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("StoreId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5208),
                            Email = "portal-admin@admin.com",
                            EmployeeTypeId = 1,
                            Name = "Portal",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            StoreId = 1,
                            Surname = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5244),
                            Email = "client-admin@company.com",
                            EmployeeTypeId = 1,
                            Name = "Client",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            StoreId = 1,
                            Surname = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Active = false,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5379),
                            Email = "client-creator@company.com",
                            EmployeeTypeId = 1,
                            Name = "Client",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            StoreId = 1,
                            Surname = "Creator"
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5404),
                            Email = "client-assigner@company.com",
                            EmployeeTypeId = 1,
                            Name = "Client",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            StoreId = 1,
                            Surname = "Assigner"
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5429),
                            Email = "client-assessor@company.com",
                            EmployeeTypeId = 1,
                            Name = "Client",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            StoreId = 1,
                            Surname = "Assessor"
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5453),
                            Email = "agency-admin@agency.com",
                            EmployeeTypeId = 1,
                            Name = "Agency",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            Surname = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            Active = false,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5510),
                            Email = "agency-supervisor@agency.com",
                            EmployeeTypeId = 1,
                            Name = "Agency",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            Surname = "Supervisor"
                        },
                        new
                        {
                            Id = 8,
                            Active = false,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 4, 17, 18, 14, 1, 848, DateTimeKind.Local).AddTicks(5536),
                            Email = "agency-agent@agency.com",
                            EmployeeTypeId = 1,
                            Name = "Agency",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            Surname = "Supervisor"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("app.Data.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Data.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("app.Data.Entity.Product", b =>
                {
                    b.HasOne("app.Data.Entity.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId");

                    b.HasOne("app.Data.Entity.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Product")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("app.Data.Entity.StoreStock", b =>
                {
                    b.HasOne("app.Data.Entity.Product", "Product")
                        .WithMany("StoreStock")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Data.Entity.Store", "Store")
                        .WithMany("StoreStock")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("app.Data.Entity.Transaction", b =>
                {
                    b.HasOne("app.Data.Entity.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Data.Entity.Store", "ToStore")
                        .WithMany()
                        .HasForeignKey("ToStoreId");

                    b.HasOne("app.Data.Entity.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("ToStore");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("app.Data.Entity.TransactionDetail", b =>
                {
                    b.HasOne("app.Data.Entity.Product", "Product")
                        .WithMany("TransactionDetail")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Data.Entity.Transaction", "Transaction")
                        .WithMany("TransactionDetail")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("app.Data.Entity.User", b =>
                {
                    b.HasOne("app.Data.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("app.Data.Entity.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId");

                    b.HasOne("app.Data.Entity.Store", "Store")
                        .WithMany("User")
                        .HasForeignKey("StoreId");

                    b.Navigation("Category");

                    b.Navigation("EmployeeType");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("app.Data.Entity.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("app.Data.Entity.Product", b =>
                {
                    b.Navigation("StoreStock");

                    b.Navigation("TransactionDetail");
                });

            modelBuilder.Entity("app.Data.Entity.Store", b =>
                {
                    b.Navigation("StoreStock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("app.Data.Entity.Transaction", b =>
                {
                    b.Navigation("TransactionDetail");
                });

            modelBuilder.Entity("app.Data.Entity.UnitOfMeasure", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
